name: Build and Test

on:
  push:
    branches: [ master ]
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'


    - name: Build
      run: mvn -B package --file pom.xml
    - name: Junit Test with Maven
      run: mvn -B test --file pom.xml

