name: Build and Test

on:
  push:
    branches: [ master ]
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'


    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Junit Test with Maven
      run: mvn -B test --file pom.xml

    - name: Deploy to Firebase
      uses: joinflux/firebase-tools@master
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
          firebase use mongodb-spring-boot
          firebase deploy --only hosting

