name: Build and Test

on:
  push:
    branches: [ master ]
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Install firebase-tools
      run: npm install -g firebase-tools

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Junit Test with Maven
      run: mvn -B test --file pom.xml

    - name: Use Firebase project
      run: firebase use mongodb-spring-boot
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Deploy to Firebase
      uses: joinflux/firebase-tools@master
      with:
          args: deploy --only hosting
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

